Fix generate flashfile image failed
Flashfile gordon_peak-flashfiles-eng.binly.zip generating error:
Exception: property not found in build.prop: ro.product.name,
due to Google removed property: "ro.product.name" in buildinfo
and add 'ro.product.${partition}.name' in buildinfo_common.

Change-Id: Idc7c0ad9a17256e73cdd080c605f0e57a5f47f86
Tracked-On: OAM-79220
Signed-off-by: jwu55 <ji.j.wu@intel.com>
Reviewed-on: 666278