Allow to process large zipfile as zip64 format
If allowZip64 is False, there will be exception for large files more than 4GB.
Exception: zipfile.LargeZipFile: Zipfile size would require ZIP64 extensions.

Jira: None.
Test: Test it on KBL-NUC.

Signed-off-by: Zhou, Lihua <lihuax.zhou@intel.com>